### ISSUE TITLE
CentOS 7 Cannot Install

### ISSUE THREAD

**Issue by MemoriseXuxu** [FoamScience/foam-language-server#10] opened 2022-03-01 07:22 UTC
I have tried several ways to insatll it, but it still turn out the same bad result.
BTW--
cmake -- 3.22.2
npm --  8.5.2

[2022-03-01T07_17_43_014Z-debug-0.log](https://github.com/FoamScience/foam-language-server/files/8159531/2022-03-01T07_17_43_014Z-debug-0.log)

**Comment by FoamScience** [comment] 2022-03-01 07:34
Node version please?
I'll try to reproduce on a centos7 container asap as I don't have it at hand right now; Thanks for reporting!

**Comment by MemoriseXuxu** [comment] 2022-03-01 09:02
The version of Node is  v16.13.2.Thank you very much. And because some calculation node is using older version of CentOS and as a result, I cannot upgrade the system.

**Comment by FoamScience** [comment] 2022-03-01 09:04
Just noticed your log file 😄 
It looks your compiler is pretty old (Still running on g++ 4.x?) Maybe upgrading to g++ 9 will help

**Comment by MemoriseXuxu** [comment] 2022-03-01 09:05
OK! I will TRY it! Thx

**Comment by FoamScience** [comment] 2022-03-01 09:17
Yes, it works for me now on a container which has `Development Tools` group and `devtoolset-9` installed and enabled.
Please confirm if it's the case for you too when you have a chance

**Comment by MemoriseXuxu** [comment] 2022-03-01 10:37
Thx!!!! The old computer have knwon the code written by YOU!

**Comment by FoamScience** [comment] 2022-03-01 10:38
Glad that helped; closing this now; feel free to re-open if anything else comes up

**Closed by FoamScience** 2022-03-01 10:38 UTC
Labels: bug
